apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-nginx-controller
spec:
  template:
    spec:
      containers:
      - name: controller
        volumeMounts:
        - name: maintenance-volume
          mountPath: /etc/nginx/maintenance
          readOnly: true
      volumes:
      - name: maintenance-volume
        configMap:
          name: maintenance
