kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:

# Deploy cert-manager as part of the bootstrap process so that it's running before its CRD resources are created
- ${K8S_GIT_URL}/k8s-configs/cluster-tools/base/cert-manager/base?ref=${K8S_GIT_BRANCH}

# generate-cluster-state.sh copies this from code-gen/templates/fluxcd/common/
# The minimal bootstrap required for the ping-cloud stack
- ping-cloud.yaml

# PDO-10506: Deploy sealed-secrets via Helm as part of bootstrap so it is available before the ping-cloud stack starts
helmCharts:
  - name: p1as-cluster-tools
    releaseName: p1as-cluster-tools-bootstrap
    includeCRDs: true
    valuesInline:
      global:
        sealedSecretsEnabled: true
        ingressNginxPublicEnabled: false
        ingressNginxPrivateEnabled: false
        karpenterEnabled: false
        karpenterCrdEnabled: false
    version: 2.4-release-branch-latest
    repo: oci://${ECR_REGISTRY_NAME}/dev
