kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- cert-manager
- cluster-autoscaler
- service-discovery
- health
- logging
- monitoring
# - security  # PDO-10506: sealed-secrets moved to p1as-cluster-tools Helm sub-chart
- pod-reaper
- kube-downscaler
